import { ModuleConfig, ModuleId } from "@/types/modules";

export const modulesConfig: Record<ModuleId, ModuleConfig> = {
  auth: {
    id: "auth",
    name: "Authentication",
    description: "User authentication and profile management",
    enabled: true,
    icon: "shield",
    path: "/auth",
  },
  goals: {
    id: "goals",
    name: "Goals",
    description: "Set and track your personal and professional goals",
    enabled: true,
    icon: "target",
    path: "/goals",
  },
  tasks: {
    id: "tasks",
    name: "Tasks",
    description: "Manage your daily tasks and to-dos",
    enabled: true,
    icon: "check-square",
    path: "/tasks",
  },
  habits: {
    id: "habits",
    name: "Habits",
    description: "Build and track positive habits",
    enabled: false,
    icon: "repeat",
    path: "/habits",
  },
  projects: {
    id: "projects",
    name: "Projects",
    description: "Organize and manage your projects",
    enabled: false,
    icon: "folder",
    path: "/projects",
  },
  reflections: {
    id: "reflections",
    name: "Reflections",
    description: "Daily reflections and journaling",
    enabled: false,
    icon: "book-open",
    path: "/reflections",
  },
  "ai-insights": {
    id: "ai-insights",
    name: "AI Insights",
    description: "Get AI-powered productivity insights",
    enabled: false,
    icon: "sparkles",
    path: "/ai-insights",
  },
  "team-collaboration": {
    id: "team-collaboration",
    name: "Team Collaboration",
    description: "Collaborate with your team",
    enabled: false,
    icon: "users",
    path: "/team",
    requiredRole: ["team_lead", "admin", "enterprise"],
  },
  "process-inventory": {
    id: "process-inventory",
    name: "Process Inventory",
    description: "Document and manage your processes",
    enabled: false,
    icon: "workflow",
    path: "/processes",
  },
};
