import { ModuleConfig, ModuleId } from "@/types/modules";

export const modulesConfig: Record<ModuleId, ModuleConfig> = {
  auth: {
    id: "auth",
    name: "Authentication",
    description: "User authentication and profile management",
    enabled: true,
    icon: "shield",
    path: "/auth",
  },
  goals: {
    id: "goals",
    name: "Goals",
    description: "Set and track your personal and professional goals",
    enabled: true,
    icon: "target",
    path: "/goals",
  },
  tasks: {
    id: "tasks",
    name: "Tasks",
    description: "Manage your daily tasks and to-dos",
    enabled: true,
    icon: "check-square",
    path: "/tasks",
  },
  "quick-todos": {
    id: "quick-todos",
    name: "Travel Notes",
    description: "Quick thoughts and reminders for your journey",
    enabled: true,
    icon: "sticky-note",
    path: "/quick-todos",
  },
  habits: {
    id: "habits",
    name: "Habits",
    description: "Build and track positive habits",
    enabled: true,
    icon: "repeat",
    path: "/habits",
  },
  projects: {
    id: "projects",
    name: "Projects",
    description: "Organize and manage your projects",
    enabled: true,
    icon: "folder",
    path: "/projects",
  },
  reflections: {
    id: "reflections",
    name: "Reflections",
    description: "Daily reflections and journaling",
    enabled: true,
    icon: "book-open",
    path: "/reflections",
  },
  notes: {
    id: "notes",
    name: "Knowledge Notes",
    description: "Zettelkasten-style note-taking and knowledge management",
    enabled: true,
    icon: "notebook",
    path: "/notes",
  },
  gamification: {
    id: "gamification",
    name: "Journey Progress",
    description: "Track your productivity level, achievements, and growth",
    enabled: true,
    icon: "trophy",
    path: "/gamification",
  },
  "productivity-profile": {
    id: "productivity-profile",
    name: "Productivity Profile",
    description: "Discover your productivity style and get personalized insights",
    enabled: true,
    icon: "user-circle",
    path: "/profile-assessment",
  },
  "ai-insights": {
    id: "ai-insights",
    name: "AI Insights",
    description: "Get AI-powered productivity insights",
    enabled: true,
    icon: "sparkles",
    path: "/ai-insights",
  },
  "team-collaboration": {
    id: "team-collaboration",
    name: "Team Collaboration",
    description: "Collaborate with your team",
    enabled: false,
    icon: "users",
    path: "/team",
    requiredRole: ["team_lead", "admin", "enterprise"],
  },
  "process-inventory": {
    id: "process-inventory",
    name: "Process Inventory",
    description: "Document and manage your processes",
    enabled: false,
    icon: "workflow",
    path: "/processes",
  },
  "api-management": {
    id: "api-management",
    name: "API Management",
    description: "Manage API connections, monitor usage, and control costs",
    enabled: true,
    icon: "key",
    path: "/admin/api-management",
    requiredRole: ["super_admin"],
  },
};
