/**
 * Navigation Hub Definitions
 * Configuration for the 6 main navigation hubs in the enhanced Luna orbital system
 */

import {
  Home,
  Calendar,
  Users,
  User,
  BarChart3,
  Settings,
  Search,
  Target,
  CheckSquare,
  StickyNote,
  Repeat,
  Folder,
  BookOpen,
  Notebook,
  Trophy,
  UserCircle,
  Sparkles,
  Clock,
  Timer,
  Goal,
  MessageSquare,
  Share,
  Video,
  Bell,
  Shield,
  CreditCard,
  Accessibility,
  Key,
  Users2,
  Building,
  Globe,
  Workflow,
  BarChart,
  Zap,
  FileText,
  PlusCircle,
  Calendar as CalendarIcon,
  Brain,
  TrendingUp,
  Award,
  Activity,
} from 'lucide-react';

import { NavigationHub } from '@/types/navigation';

/**
 * Get all navigation hub definitions
 */
export function getNavigationHubDefinitions(): NavigationHub[] {
  return [
    // Hub 1: Capture & Productivity
    {
      id: 'capture-productivity',
      name: 'Capture & Productivity',
      description: 'Quick capture thoughts, tasks, and productive workflows',
      icon: Target,
      color: 'bg-blue-500 hover:bg-blue-600',
      path: '/app/capture',
      priority: 1,
      customizable: true,
      contextRules: [
        {
          type: 'path',
          condition: '/app/capture',
          weight: 1.0,
          operator: 'contains',
        },
        {
          type: 'path',
          condition: '/tasks',
          weight: 0.8,
          operator: 'contains',
        },
        {
          type: 'workflow',
          condition: 'executing',
          weight: 0.9,
        },
      ],
      subNavigation: [
        {
          id: 'quick-tasks',
          label: 'Quick Tasks',
          icon: CheckSquare,
          path: '/tasks',
          description: 'Manage your daily tasks and to-dos',
          shortcut: '⌘T',
          contextRelevance: 1.0,
        },
        {
          id: 'notes',
          label: 'Notes',
          icon: Notebook,
          path: '/notes',
          description: 'Knowledge notes and documentation',
          shortcut: '⌘N',
          contextRelevance: 0.8,
        },
        {
          id: 'projects',
          label: 'Projects',
          icon: Folder,
          path: '/projects',
          description: 'Organize and manage your projects',
          shortcut: '⌘P',
          contextRelevance: 0.7,
        },
        {
          id: 'habits',
          label: 'Habits',
          icon: Repeat,
          path: '/habits',
          description: 'Build and track positive habits',
          shortcut: '⌘H',
          contextRelevance: 0.6,
        },
        {
          id: 'reflections',
          label: 'Reflections',
          icon: BookOpen,
          path: '/reflections',
          description: 'Daily reflections and journaling',
          shortcut: '⌘R',
          contextRelevance: 0.5,
        },
        {
          id: 'quick-todos',
          label: 'Travel Notes',
          icon: StickyNote,
          path: '/quick-todos',
          description: 'Quick thoughts and reminders',
          contextRelevance: 0.4,
        },
      ],
      quickActions: [
        {
          id: 'new-task',
          label: 'New Task',
          icon: PlusCircle,
          action: () => console.log('Creating new task'),
          color: 'bg-blue-500',
          shortcut: '⌘⇧T',
          contextRules: [
            {
              type: 'path',
              condition: '/app/capture',
              weight: 1.0,
            },
          ],
        },
        {
          id: 'quick-note',
          label: 'Quick Note',
          icon: FileText,
          action: () => console.log('Creating quick note'),
          color: 'bg-green-500',
          shortcut: '⌘⇧N',
          contextRules: [
            {
              type: 'workflow',
              condition: 'executing',
              weight: 0.8,
            },
          ],
        },
      ],
    },

    // Hub 2: Planning & Time Management
    {
      id: 'planning-time',
      name: 'Planning & Time',
      description: 'Organize your schedule and plan your future',
      icon: Calendar,
      color: 'bg-green-500 hover:bg-green-600',
      path: '/app/plan',
      priority: 2,
      customizable: true,
      contextRules: [
        {
          type: 'path',
          condition: '/app/plan',
          weight: 1.0,
          operator: 'contains',
        },
        {
          type: 'time',
          condition: 'morning',
          weight: 0.7,
        },
        {
          type: 'workflow',
          condition: 'planning',
          weight: 0.9,
        },
      ],
      subNavigation: [
        {
          id: 'calendar',
          label: 'Calendar',
          icon: CalendarIcon,
          path: '/calendar',
          description: 'View and manage your schedule',
          shortcut: '⌘C',
          contextRelevance: 1.0,
        },
        {
          id: 'goals',
          label: 'Goals',
          icon: Goal,
          path: '/goals',
          description: 'Set and track your goals',
          shortcut: '⌘G',
          contextRelevance: 0.9,
        },
        {
          id: 'time-blocking',
          label: 'Time Blocking',
          icon: Clock,
          path: '/time-blocking',
          description: 'Plan focused work sessions',
          shortcut: '⌘B',
          contextRelevance: 0.8,
        },
        {
          id: 'pomodoro',
          label: 'Focus Timer',
          icon: Timer,
          path: '/pomodoro',
          description: 'Pomodoro technique timer',
          shortcut: '⌘F',
          contextRelevance: 0.7,
        },
      ],
      quickActions: [
        {
          id: 'new-event',
          label: 'New Event',
          icon: CalendarIcon,
          action: () => console.log('Creating new event'),
          color: 'bg-green-500',
          shortcut: '⌘⇧E',
          contextRules: [
            {
              type: 'path',
              condition: '/app/plan',
              weight: 1.0,
            },
          ],
        },
        {
          id: 'focus-session',
          label: 'Start Focus',
          icon: Timer,
          action: () => console.log('Starting focus session'),
          color: 'bg-orange-500',
          shortcut: '⌘⇧F',
          contextRules: [
            {
              type: 'time',
              condition: 'working-hours',
              weight: 0.9,
            },
          ],
        },
      ],
    },

    // Hub 3: Engage & Collaboration
    {
      id: 'engage-collaboration',
      name: 'Engage & Collaborate',
      description: 'Connect and work with your team',
      icon: Users,
      color: 'bg-indigo-500 hover:bg-indigo-600',
      path: '/app/engage',
      priority: 3,
      customizable: true,
      contextRules: [
        {
          type: 'path',
          condition: '/app/engage',
          weight: 1.0,
          operator: 'contains',
        },
        {
          type: 'user-role',
          condition: 'team_lead',
          weight: 0.8,
        },
        {
          type: 'workflow',
          condition: 'collaborating',
          weight: 0.9,
        },
      ],
      subNavigation: [
        {
          id: 'team-projects',
          label: 'Team Projects',
          icon: Users2,
          path: '/team',
          description: 'Collaborative team projects',
          requiredRole: ['team_lead', 'admin', 'enterprise'],
          contextRelevance: 1.0,
        },
        {
          id: 'meetings',
          label: 'Meetings',
          icon: Video,
          path: '/meetings',
          description: 'Schedule and join meetings',
          contextRelevance: 0.9,
        },
        {
          id: 'shared-docs',
          label: 'Shared Docs',
          icon: Share,
          path: '/shared-docs',
          description: 'Collaborative documents',
          contextRelevance: 0.8,
        },
        {
          id: 'notifications',
          label: 'Notifications',
          icon: Bell,
          path: '/notifications',
          description: 'Team updates and alerts',
          contextRelevance: 0.7,
        },
      ],
      quickActions: [
        {
          id: 'start-meeting',
          label: 'Start Meeting',
          icon: Video,
          action: () => console.log('Starting meeting'),
          color: 'bg-indigo-500',
          shortcut: '⌘⇧M',
          contextRules: [
            {
              type: 'user-role',
              condition: 'team_lead',
              weight: 0.9,
            },
          ],
        },
        {
          id: 'send-message',
          label: 'Send Message',
          icon: MessageSquare,
          action: () => console.log('Sending message'),
          color: 'bg-purple-500',
          shortcut: '⌘⇧S',
          contextRules: [
            {
              type: 'workflow',
              condition: 'collaborating',
              weight: 0.8,
            },
          ],
        },
      ],
    },

    // Hub 4: Profile & User Management
    {
      id: 'profile-user',
      name: 'Profile & Settings',
      description: 'Manage your account and preferences',
      icon: User,
      color: 'bg-yellow-500 hover:bg-yellow-600',
      path: '/app/profile',
      priority: 4,
      customizable: true,
      contextRules: [
        {
          type: 'path',
          condition: '/app/profile',
          weight: 1.0,
          operator: 'contains',
        },
        {
          type: 'path',
          condition: '/settings',
          weight: 0.8,
          operator: 'contains',
        },
      ],
      subNavigation: [
        {
          id: 'user-profile',
          label: 'Profile',
          icon: UserCircle,
          path: '/profile',
          description: 'Your personal profile',
          contextRelevance: 1.0,
        },
        {
          id: 'account-settings',
          label: 'Account',
          icon: Settings,
          path: '/account-settings',
          description: 'Account preferences',
          contextRelevance: 0.9,
        },
        {
          id: 'accessibility',
          label: 'Accessibility',
          icon: Accessibility,
          path: '/settings/accessibility',
          description: 'Accessibility options',
          contextRelevance: 0.8,
        },
        {
          id: 'billing',
          label: 'Billing',
          icon: CreditCard,
          path: '/billing',
          description: 'Subscription and billing',
          contextRelevance: 0.6,
        },
        {
          id: 'security',
          label: 'Security',
          icon: Shield,
          path: '/security',
          description: 'Security settings',
          contextRelevance: 0.7,
        },
      ],
      quickActions: [
        {
          id: 'update-profile',
          label: 'Edit Profile',
          icon: UserCircle,
          action: () => console.log('Editing profile'),
          color: 'bg-yellow-500',
          shortcut: '⌘⇧P',
          contextRules: [
            {
              type: 'path',
              condition: '/app/profile',
              weight: 1.0,
            },
          ],
        },
      ],
    },

    // Hub 5: Insights & Growth (New)
    {
      id: 'insights-growth',
      name: 'Insights & Growth',
      description: 'AI-powered insights and personal development',
      icon: BarChart3,
      color: 'bg-purple-500 hover:bg-purple-600',
      path: '/analytics',
      priority: 5,
      customizable: true,
      contextRules: [
        {
          type: 'path',
          condition: '/analytics',
          weight: 1.0,
          operator: 'contains',
        },
        {
          type: 'path',
          condition: '/ai-insights',
          weight: 0.9,
          operator: 'contains',
        },
        {
          type: 'workflow',
          condition: 'reviewing',
          weight: 0.8,
        },
      ],
      subNavigation: [
        {
          id: 'analytics',
          label: 'Analytics',
          icon: BarChart,
          path: '/analytics',
          description: 'Personal productivity analytics',
          requiredRole: ['admin', 'enterprise'],
          contextRelevance: 1.0,
        },
        {
          id: 'ai-insights',
          label: 'AI Insights',
          icon: Sparkles,
          path: '/ai-insights',
          description: 'AI-powered recommendations',
          contextRelevance: 0.9,
        },
        {
          id: 'gamification',
          label: 'Progress',
          icon: Trophy,
          path: '/gamification',
          description: 'Achievements and progress tracking',
          contextRelevance: 0.8,
        },
        {
          id: 'productivity-profile',
          label: 'Profile Assessment',
          icon: Brain,
          path: '/profile-assessment',
          description: 'Discover your productivity style',
          contextRelevance: 0.7,
        },
        {
          id: 'trends',
          label: 'Trends',
          icon: TrendingUp,
          path: '/trends',
          description: 'Performance trends and patterns',
          contextRelevance: 0.6,
        },
      ],
      quickActions: [
        {
          id: 'view-insights',
          label: 'View Insights',
          icon: Sparkles,
          action: () => console.log('Viewing AI insights'),
          color: 'bg-purple-500',
          shortcut: '⌘⇧I',
          contextRules: [
            {
              type: 'workflow',
              condition: 'reviewing',
              weight: 0.9,
            },
          ],
        },
        {
          id: 'check-progress',
          label: 'Check Progress',
          icon: Activity,
          action: () => console.log('Checking progress'),
          color: 'bg-green-500',
          shortcut: '⌘⇧R',
          contextRules: [
            {
              type: 'time',
              condition: 'evening',
              weight: 0.8,
            },
          ],
        },
      ],
    },

    // Hub 6: Advanced & Admin Tools (New)
    {
      id: 'advanced-admin',
      name: 'Advanced & Admin',
      description: 'Advanced tools and administrative functions',
      icon: Settings,
      color: 'bg-gray-500 hover:bg-gray-600',
      path: '/admin',
      priority: 6,
      customizable: false,
      requiredRole: ['admin', 'super_admin'],
      contextRules: [
        {
          type: 'user-role',
          condition: 'admin',
          weight: 1.0,
        },
        {
          type: 'user-role',
          condition: 'super_admin',
          weight: 1.0,
        },
        {
          type: 'path',
          condition: '/admin',
          weight: 0.9,
          operator: 'contains',
        },
      ],
      subNavigation: [
        {
          id: 'api-management',
          label: 'API Management',
          icon: Key,
          path: '/admin/api',
          description: 'Manage API connections and usage',
          requiredRole: ['super_admin'],
          contextRelevance: 1.0,
        },
        {
          id: 'user-management',
          label: 'Users',
          icon: Users,
          path: '/admin/users',
          description: 'User management and permissions',
          requiredRole: ['admin', 'super_admin'],
          contextRelevance: 0.9,
        },
        {
          id: 'system-health',
          label: 'System Health',
          icon: Activity,
          path: '/admin/health',
          description: 'System monitoring and health',
          requiredRole: ['admin', 'super_admin'],
          contextRelevance: 0.8,
        },
        {
          id: 'integrations',
          label: 'Integrations',
          icon: Globe,
          path: '/integrations',
          description: 'Third-party integrations',
          requiredRole: ['team_lead', 'admin', 'enterprise'],
          contextRelevance: 0.7,
        },
        {
          id: 'enterprise',
          label: 'Enterprise',
          icon: Building,
          path: '/enterprise',
          description: 'Enterprise management',
          requiredRole: ['admin', 'enterprise'],
          contextRelevance: 0.6,
        },
      ],
      quickActions: [
        {
          id: 'system-check',
          label: 'System Check',
          icon: Activity,
          action: () => console.log('Running system check'),
          color: 'bg-red-500',
          shortcut: '⌘⇧H',
          contextRules: [
            {
              type: 'user-role',
              condition: 'super_admin',
              weight: 1.0,
            },
          ],
        },
      ],
    },

    // Hub 7: Search Assistant (Enhanced)
    {
      id: 'search-assistant',
      name: 'Search & Assistant',
      description: 'AI-powered search and intelligent assistance',
      icon: Search,
      color: 'bg-slate-500 hover:bg-slate-600',
      path: '/search',
      priority: 7,
      customizable: true,
      contextRules: [
        {
          type: 'workflow',
          condition: 'general',
          weight: 0.5,
        },
      ],
      subNavigation: [
        {
          id: 'global-search',
          label: 'Global Search',
          icon: Search,
          path: '/search',
          description: 'Search across all content',
          shortcut: '⌘K',
          contextRelevance: 1.0,
        },
        {
          id: 'ai-assistant',
          label: 'AI Assistant',
          icon: Brain,
          path: '/assistant',
          description: 'AI-powered assistant',
          shortcut: '⌘⇧A',
          contextRelevance: 0.9,
        },
        {
          id: 'command-center',
          label: 'Command Center',
          icon: Zap,
          path: '/luna',
          description: 'Luna command center',
          contextRelevance: 0.8,
        },
      ],
      quickActions: [
        {
          id: 'quick-search',
          label: 'Quick Search',
          icon: Search,
          action: () => console.log('Opening search'),
          color: 'bg-slate-500',
          shortcut: '⌘K',
          contextRules: [
            {
              type: 'workflow',
              condition: 'general',
              weight: 1.0,
            },
          ],
        },
      ],
    },
  ];
}