name: BeProductive-iOS
options:
  bundleIdPrefix: com.beproductive
  deploymentTarget:
    iOS: 17.0
  developmentLanguage: en
  createIntermediateGroups: true

fileGroups:
  - Sources
  - Resources

packages:
  BeProductiveUI:
    path: ../BeProductiveUI
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: 2.8.0
  Algorithms:
    url: https://github.com/apple/swift-algorithms.git
    from: 1.2.0
  Collections:
    url: https://github.com/apple/swift-collections.git
    from: 1.1.0
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    from: 1.15.0
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 12.8.0
  Starscream:
    url: https://github.com/daltoniam/Starscream.git
    from: 4.0.8
  SwiftyJSON:
    url: https://github.com/SwiftyJSON/SwiftyJSON.git
    from: 5.0.2
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    from: 7.12.0

targets:
  BeProductive-iOS:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beproductive.ios
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        ENABLE_BITCODE: false
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        SWIFT_EMIT_LOC_STRINGS: true
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
          OTHER_SWIFT_FLAGS: -DDEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
          SWIFT_OPTIMIZATION_LEVEL: -O
    dependencies:
      - package: BeProductiveUI
        product: BeProductiveUI
      - package: Supabase
        product: Supabase
      - package: Algorithms
        product: Algorithms
      - package: Collections
        product: Collections
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: Nuke
        product: Nuke
      - package: Nuke
        product: NukeUI
      - package: Starscream
        product: Starscream
      - package: SwiftyJSON
        product: SwiftyJSON
      - package: Kingfisher
        product: Kingfisher

  BeProductive-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: BeProductive-iOS
    settings:
      base:
        BUNDLE_LOADER: $(TEST_HOST)
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/BeProductive-iOS.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/BeProductive-iOS
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

  BeProductive-iOSUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - UITests
    dependencies:
      - target: BeProductive-iOS
    settings:
      base:
        TEST_TARGET_NAME: BeProductive-iOS
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

schemes:
  BeProductive-iOS:
    build:
      targets:
        BeProductive-iOS: all
        BeProductive-iOSTests: [test]
        BeProductive-iOSUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - BeProductive-iOSTests
        - BeProductive-iOSUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release