import { useNavigate } from 'react-router-dom';
import {
  FileText,
  Target,
  CheckSquare,
  MessageCircle,
  Zap,
  FolderOpen,
  RotateCcw,
  Tag,
  Calendar,
  BarChart3,
  Settings,
  BookOpen,
  Clock,
  Users,
  Lightbulb,
  Star,
  Archive,
  Edit3,
  Plus,
  Search,
  Filter,
  Share2,
} from 'lucide-react';
import { CarouselCategory } from './types';
import { lunaColors } from '../design/DesignTokens';

export const useCarouselData = (): CarouselCategory[] => {
  const navigate = useNavigate();

  return [
    {
      id: 'capture',
      label: 'Capture',
      icon: Plus,
      color: lunaColors.categories.capture.gradient,
      items: [
        {
          id: 'notes',
          label: 'Note',
          icon: FileText,
          action: () => navigate('/notes'),
          description: 'Capture thoughts quickly',
        },
        {
          id: 'tasks',
          label: 'Task',
          icon: CheckSquare,
          action: () => navigate('/tasks'),
          description: 'Add to your todo list',
        },
        {
          id: 'quick-todos',
          label: 'Quick To-Do',
          icon: Zap,
          action: () => navigate('/quick-todos'),
          description: 'Rapid task capture',
        },
        {
          id: 'reflections',
          label: 'Reflection',
          icon: MessageCircle,
          action: () => navigate('/reflections'),
          description: 'Record an insight',
        },
      ],
    },
    {
      id: 'plan',
      label: 'Plan',
      icon: Target,
      color: lunaColors.categories.plan.gradient,
      items: [
        {
          id: 'goals',
          label: 'Goal',
          icon: Target,
          action: () => navigate('/goals/new'),
          description: 'Set a new objective',
        },
        {
          id: 'projects',
          label: 'Project',
          icon: FolderOpen,
          action: () => navigate('/projects'),
          description: 'Start something new',
        },
        {
          id: 'habits',
          label: 'Habit',
          icon: RotateCcw,
          action: () => navigate('/habits'),
          description: 'Build consistency',
        },
        {
          id: 'calendar',
          label: 'Schedule',
          icon: Calendar,
          action: () => navigate('/calendar'),
          description: 'Plan your time',
        },
      ],
    },
    {
      id: 'organize',
      label: 'Organize',
      icon: Tag,
      color: lunaColors.categories.organize.gradient,
      items: [
        {
          id: 'tags',
          label: 'Tags',
          icon: Tag,
          action: () => navigate('/tags'),
          description: 'Organize content',
        },
        {
          id: 'search',
          label: 'Search',
          icon: Search,
          action: () => navigate('/search'),
          description: 'Find anything',
        },
        {
          id: 'filter',
          label: 'Filter',
          icon: Filter,
          action: () => navigate('/filter'),
          description: 'Sort and filter',
        },
        {
          id: 'archive',
          label: 'Archive',
          icon: Archive,
          action: () => navigate('/archive'),
          description: 'Archived items',
        },
      ],
    },
    {
      id: 'track',
      label: 'Track',
      icon: BarChart3,
      color: lunaColors.categories.track.gradient,
      items: [
        {
          id: 'analytics',
          label: 'Analytics',
          icon: BarChart3,
          action: () => navigate('/analytics'),
          description: 'View progress',
        },
        {
          id: 'time-tracking',
          label: 'Time',
          icon: Clock,
          action: () => navigate('/time-tracking'),
          description: 'Track time spent',
        },
        {
          id: 'habits-progress',
          label: 'Habits',
          icon: RotateCcw,
          action: () => navigate('/habits'),
          description: 'Habit streaks',
        },
        {
          id: 'goals-progress',
          label: 'Goals',
          icon: Target,
          action: () => navigate('/goals'),
          description: 'Goal progress',
        },
      ],
    },
    {
      id: 'collaborate',
      label: 'Share',
      icon: Users,
      color: lunaColors.categories.share.gradient,
      items: [
        {
          id: 'share',
          label: 'Share',
          icon: Share2,
          action: () => navigate('/share'),
          description: 'Share content',
        },
        {
          id: 'teams',
          label: 'Teams',
          icon: Users,
          action: () => navigate('/teams'),
          description: 'Collaborate',
        },
        {
          id: 'feedback',
          label: 'Feedback',
          icon: MessageCircle,
          action: () => navigate('/feedback'),
          description: 'Give feedback',
        },
        {
          id: 'ideas',
          label: 'Ideas',
          icon: Lightbulb,
          action: () => navigate('/ideas'),
          description: 'Share ideas',
        },
      ],
    },
    {
      id: 'learn',
      label: 'Learn',
      icon: BookOpen,
      color: lunaColors.categories.learn.gradient,
      items: [
        {
          id: 'tutorials',
          label: 'Tutorials',
          icon: BookOpen,
          action: () => navigate('/tutorials'),
          description: 'Learn how to',
        },
        {
          id: 'tips',
          label: 'Tips',
          icon: Lightbulb,
          action: () => navigate('/tips'),
          description: 'Pro tips',
        },
        {
          id: 'templates',
          label: 'Templates',
          icon: Edit3,
          action: () => navigate('/templates'),
          description: 'Use templates',
        },
        {
          id: 'best-practices',
          label: 'Best Practices',
          icon: Star,
          action: () => navigate('/best-practices'),
          description: 'Learn patterns',
        },
      ],
    },
  ];
};